# Base configs
baseurl: "https://Saatvikbhayana.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Saatvik Bhayana Photography"
subtitle: "See the world through my eyes!"
author: "Saatvik Bhayana"
header:
 title: "Photography"
 subtitle: "by Saatvik Bhayana"
footer:
 name: "Hey there, my name is Saatvik"
 bio: "I am a developer and a tech aficionado from Toronto. With a love for beautiful views, I decided to pick up photography to try to share the world through my eyes."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
 # facebook: "https://www.facebook.com/ramswaroop"
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/sb.photography.guelph"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/thatguy2137"
